---
- name: Get Show Counters for Jericho
  hosts: arista
  gather_facts: False

  tasks:
    - name: Check if file needs to be created
      local_action: stat path=./{{ inventory_hostname }}cpucounters
      register: doesfileexist
    - name: Create file if needed
      file:
        path: "./{{ inventory_hostname }}cpucounters"
        state: touch
        mode: 0755
      when: doesfileexist.stat.exists == false
    - name: Check if file needs to be created
      local_action: stat path=./{{ inventory_hostname }}cpucounters
      register: doesfileexist
    - name: Create file if needed
      file:
        path: "./{{ inventory_hostname }}cpucounters"
        state: touch
        mode: 0755
      when: doesfileexist.stat.exists == false
    - name: Get Counter Output
      eos_command:
        commands:
        - command: show cpu counters queue
          output: json
      register: cpu_counters
    - name: Verify the list of CPUs
      set_fact: 
        cpulst: "{{ cpu_counters.stdout[0]['ingressVoqs']['sources'] | list }}"
    - name: Send to files
      local_action: lineinfile line="{{ lookup('pipe','date') }} {{ item }} CoppSystemVxlanEncap - droppedBytes were {{ cpu_counters.stdout[0]['ingressVoqs']['sources'][item]['cpuClasses']['CoppSystemVxlanEncap']['ports']['']['droppedBytes'] }} - droppedPackets were {{ cpu_counters.stdout[0]['ingressVoqs']['sources'][item]['cpuClasses']['CoppSystemVxlanEncap']['ports']['']['droppedPackets']}}" insertafter=EOF dest=./{{ inventory_hostname }}cpucounters
      loop: "{{ cpulst }}"
